title = "Moba Genie"
baseurl = "https://www.mobagenie.id"
#baseurl = "http://localhost:1313rrr"

# Agar front-matter pakai format YAML
MetaDataFormat = "yaml"

# untuk apply temanya
themesDir = "themes"
theme = "viomagz"

[taxonomies]
  category = "categories"
  tag = "tags"
  
[permalinks]
    post = "/:slug/"
	   # post = "/:year/:month/:day/:slug/"
   

# Shortname disqus, silahkan sesuaikan
DisqusShortname = "mobagenie"

# Untuk Google Analytic, silahkan sesuikan
googleAnalytics = "UA-80517197-1" 

# Untuk deskripsi tag meta di homepage
description = "Blog Programmer pengguna Linux"

# Biodata Author
[author]
    name = "Moba Genie"
    homepage = "https://twitter.com/mobagenie"
    bio = "noo"
    image = "https://lh5.googleusercontent.com/-h2tLsyijw8Q/AAAAAAAAAAI/AAAAAAAACys/WBpjN_34z3o/s32-c/photo.jpg"

